---
- hosts: localhost

  tasks:
    - include_vars: inventories/prod/group_vars/ebsmount_ptc

    - name: run ebs mount app
      shell: "/common/unixadmins/micky/scripts/ebstest.ksh m {{ item.host }} {{ item.fsmount }} {{ item.fstab }}"
      with_items: "{{ app_servers }}"
    - name: run ebs mount db
      shell: "/common/unixadmins/micky/scripts/ebstest.ksh m {{ item.host }} {{ item.fsmount }} {{ item.fstab }}"
      with_items: "{{ db_servers }}"
