---
- hosts: "{{ host_name }}"
  tasks:
    - name: install start script
      copy:
        src: /common/sysadminapps/telegraf/solaris/script/telegraf
        dest: /etc/init.d/
        mode: '0744'
    - name: make dir
      file:
        path: /etc/telegraf
        state: directory
        mode: '0755'
    - name: telegraf install
      copy:
        src: /common/sysadminapps/telegraf/solaris/bin/telegraf
        dest: /usr/bin/
        mode: '0755'
    - name: install start script link
      file:
        src: /etc/init.d/telegraf
        dest: /etc/rc3.d/S93telegraf
        state: link
    - name: make link
      file:
        src: /common/sysadminapps/telegraf/solaris/opt/csw
        dest: /opt/csw
        state: link
    - name:  install conf file
      copy:
        src: /common/sysadminapps/telegraf/solaris/conf/telegraf.conf
        dest: /etc/telegraf/
    - name: start telegraf service
      shell: /etc/rc3.d/S93telegraf start
