---
- hosts: localhost
  gather_facts: false
##  - set_fact: todaysdate="{{lookup('pipe','date "+%Y/%m/%d %H:%M"')}}"
## two parts
  roles:
     - vm_snap_dev
     - vm_snap_poc
     - vm_snap_trn
