---
- hosts: ansprdapp11
  gather_facts: false
  connection: local
  tasks:
  - include_vars: inventories/prod/group_vars/vcenter_vars_{{ environ }}
  # get date
  - set_fact: creationdate="{{lookup('pipe','date "+%Y/%m/%d %H:%M"')}}"
  # Create a VM from a template
  - name: create the VM
    vmware_guest:
      hostname: "{{ vcenter_server }}"
      username: "{{ vcenter_user }}"
      password: "{{ vcenter_pass }}"
      validate_certs: no
      esxi_hostname: "{{ esx_host }}"
      datacenter: "{{ dc_name }}"
      folder: "{{ esx_folder }}"
      name: '{{ host_name }}'
      state: poweredon
      annotation: "{{ notes }} - {{ creationdate }}"
      disk:
      - size_gb: 50
        type: thick
        datastore: "{{ esx_datastore }}"
      - size_gb: '{{ disk_size }}'
        type: thick
        datastore: "{{ esx_datastore }}"
      hardware:
        memory_mb: "{{ memory_gb *1024 }}"
        num_cpus: "{{ cpu_count }}"
##        num_cpu_cores_per_socket: "2"
      networks:
      - name: "{{ my_vlan }}"
        device_type: 'vmxnet3'
        type: 'static'
        ip: "{{ new_ipaddr }}"
        netmask: "{{ new_mask }}"
        gateway: "{{ new_gateway }}"
      customization:
        dns_servers:
          - 10.8.32.195
          - 10.7.32.195
        domain: comfort.com
        hostname: '{{ host_name }}'
      template: RHEL_7_X_64BIT_VMTOOLS
      wait_for_ip_address: yes
